### ISSUE TITLE
replace and update function returns "Invalid request: parameter validation failed. Check your request data."

### ISSUE THREAD

**Issue by ronkpunk** [bohoffi/ngx-airtable#23]
Hi, I'm developing and Ionic/Angular App using Airtable DB. I create a data service that uses ngx-airtable to read/write data on Airtable tables.

I can read correctly data from any table and I can also "create" new records.

Now  I'm trying to update records but I receive an 422 "Unprocessable Entity" error with the following response:

`{"error":{"type":"INVALID_REQUEST_UNKNOWN","message":"Invalid request: parameter validation failed. Check your request data."}}`

**To Reproduce**

 --- app.module.ts ---
`
[...]
import {NgxAirtableModule} from 'ngx-airtable';
[...]
@NgModule({
  declarations: [...],
  imports: [
    [...]
    NgxAirtableModule.forRoot({apiKey: '<myapikey>'}),
  ],
  providers: [...],
  bootstrap: [...]
})
export class AppModule {}
`

 --- data.service.ts ---
`
import { Airtable, Base } from 'ngx-airtable';
import { environment } from 'src/environments/environment';

@Injectable({
  providedIn: 'root'
})
export class DataService {
  private readonly base: Base;
  constructor(
    private readonly airtable: Airtable,
  ) {
    this.base = this.airtable.base(environment.airtableBase);
  }
    update(tableName: string, id: string, item: any): Promise<any> {
    return new Promise((resolve, reject) => {
      console.log('update', id, item);
      this.base.table({ tableName }).replace(id, item).subscribe(response => {
        console.log('update', id, item);
        resolve(response);
      });
    });
  }
  replace(tableName: string, id: string, item: any): Promise<any> {
    return new Promise((resolve, reject) => {
      console.log('replace', id, item);
      this.base.table({ tableName }).replace(id, item).subscribe(response => {
        console.log('replace', response);
        resolve(response);
      });
    });
  }
  create(tableName: string, item: any): Promise<any> {
    console.log('create', tableName, item);
    return new Promise((resolve, reject) => {
      this.base.table({ tableName }).create(item).subscribe(response => {
        console.log('create', response);
        resolve(response);
      });
    });
 }
`

--- app.component.ts ---
`
[...]
import { DataService } from './services/data.service';
[...]

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss'],
})

export class AppComponent {
    [...] 

    constructor(
        private data: DataService
      ) {

          this.data.get('<MyTable>', '<MyFilterToGetOneItem>').then(item => {
            if( item ) {
              console.log('item exists', item);
              
              item.fields.ItemStringProperty = "MyUpdatedString";

              this.data.replace('<MyTable>', item.id, item);
            }
            else 
            {
              item = {
                fields: {
                  ItemStringProperty: "MyCreatedString"
                }
              };
              this.data.create('<MyTable>', item);
            }
          });
        });
  }
}
`

1. First time my App enter in constructor, it doen't find "item" in <MyTable> so I "create" it and Airtable module do it fine
2. Second time my App enter in constructor, it find "item" in <Table> so I try to "update" or "replace" it but Airable module gives me 422 "Unprocessable Entity" error with the following response:
`{"error":{"type":"INVALID_REQUEST_UNKNOWN","message":"Invalid request: parameter validation failed. Check your request data."}}`

**Expected behavior**
I expect that, when an "item" is found in <MyTable>, if I try to "update" or "replace" it, updating fields, it doesn't give me and error.

**Version information (please complete the following information):**
 - Node 14.17.0
 - Npm 8.1.3
 - Angular: 14.0.0
 - Ionic 6.17.1
 - Capacitor: 4.0.1
 - ngx-airtable: 2.0.1-next.0

**Comment by ronkpunk** [comment]
I found by myself, I've to pass only fields without Airtable properties ('id', 'creationDate' and so on)

**Comment by bohoffi** [comment]
@ronkpunk thanks for the update on this issue

**Comment by ronkpunk** [comment]
OT, is it possible to upload files as attachment? If it's possible, how can I do that?

**Comment by bohoffi** [comment]
Ouf ^^
As stated in the [README](https://github.com/bohoffi/ngx-airtable#api) this lib is compatible to airtable.js API v0.5.0.

While the airtable.js API seems to be on v0.11.4 - and I haven't looked at it for a long while - I'm sorry to say that I can't answer your question :(
