### ISSUE TITLE
Can't compile in production mode.

### ISSUE THREAD

**Issue by misaelvillegas97** [bohoffi/ngx-airtable#6]
When i have to compile to production mode, Angular compiler gived me followed error.

`ERROR in ./node_modules/ngx-airtable/src/ngx-airtable.module.ts
Module build failed: Error: C:\Users\david\Desktop\innoapsion_pages\sistema-consulta\node_modules\ngx-airtable\src\ngx-airtable.module.ts is missing from the TypeScript compilation. Please make sure it
is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).`

![image](https://user-images.githubusercontent.com/29538430/45306090-23c50580-b4f2-11e8-92f3-6a81de6035ee.png)

**Comment by bohoffi** [comment]
Could you please provide a minimal repo for reproduction?

**Comment by misaelvillegas97** [comment]
https://github.com/misaelvillegas97/sistema-consulta
There is my repository

**Comment by ngodichat** [comment]
I have the same issue. Did you find the solution for this @bohoffi? Thank you!

**Comment by bohoffi** [comment]
@misaelvillegas97 @ngodichat 
I'm sorry for the delay but I plan to upgrade the library and while doing this the issue will get fixed.

**Comment by bohoffi** [comment]
@misaelvillegas97 @ngodichat If this is still an issue for you I've published version `ngx-airtable@2.0.1-next.0` as a Pre-release version which is compatible up to Angular 10.

**Comment by bohoffi** [comment]
As approved by https://github.com/bohoffi/ngx-airtable/issues/20 I'll close this issue as fixed
