### ISSUE TITLE
Angular 6 compatibility

### ISSUE THREAD

**Issue by ngarland79** [bohoffi/ngx-airtable#7]
I noticed that there is a package.json file in here that seems to indicate that you meant it to be compatible with Angular 6, yet the Node Package is still on version 2.0 and Angular 4. When I try to use it my Angular 6 project, I get the following error:

ERROR Error: Uncaught (in promise): TypeError: rxjs_Observable.Observable.defer is not a function
TypeError: rxjs_Observable.Observable.defer is not a function
    at Query.push../node_modules/ngx-airtable/bundles/ngx-airtable.umd.js.Query._all (ngx-airtable.umd.js:178)
    at Query.push../node_modules/ngx-airtable/bundles/ngx-airtable.umd.js.Query.all (ngx-airtable.umd.js:143)

This happens wen I use all().

firstPage() works properly.

**Comment by amanvishnani** [comment]
@bohoffi Please Update this library on [NPM](https://www.npmjs.com/package/ngx-airtable).
Looks like fix is available but not useable by the general public.

**Comment by amanvishnani** [comment]
@bohoffi Any update on this?

**Comment by frerotg** [comment]
Someone have a solution ?? I tried the package with angular 7 but it doesn't work..

**Comment by bohoffi** [comment]
@frerotg @ngarland79 @amanvishnani I've published version `ngx-airtable@2.0.1-next.0` as a Pre-release version which is compatibly up to Angular 10.

**Comment by bohoffi** [comment]
As approved by https://github.com/bohoffi/ngx-airtable/issues/20 I'll close this issue as fixed
